SPECIES_DATABASE = {

    # ==================== LAND PLANTS ====================

    "Neem": {
        "scientific_name": "Azadirachta indica",
        "type": "Plant / Tree",
        "family": "Meliaceae",
        "habitat": "Tropical and subtropical forest regions",
        "region": "India, South Asia, Southeast Asia",
        "ecological_role": "Provides dense shade, purifies air, and contributes to soil fertility.",
        "importance": "Widely valued for its antibacterial, anti-inflammatory, and agricultural uses.",
        "conservation": "Least Concern (Widespread)",
        "conserved": False,
        "estimated_population": "N/A",
        "diet": "Photosynthetic",
        "threats": "Uncontrolled urban clearing and severe drought.",
        "facts": "Neem produces azadirachtin, a natural compound used worldwide as an organic pesticide.",
    },

    "Banyan": {
        "scientific_name": "Ficus benghalensis",
        "type": "Plant / Tree",
        "family": "Moraceae",
        "habitat": "Tropical rainforests, woodlands, and sacred groves",
        "region": "India, South Asia (National Tree of India)",
        "ecological_role": "Keystone species providing fruit, roosting, and nesting for hundreds of bird species.",
        "importance": "National tree of India, sacred in traditional folklore and ecosystem stability.",
        "conservation": "Least Concern (Widespread)",
        "conserved": True,
        "estimated_population": "N/A",
        "diet": "Photosynthetic",
        "threats": "Urban encroachment and loss of pollinating fig wasps.",
        "facts": "A single Banyan tree can spread over acres via aerial prop roots that grow downward into secondary trunks.",
    },

    "Teak": {
        "scientific_name": "Tectona grandis",
        "type": "Plant / Tree",
        "family": "Lamiaceae",
        "habitat": "Tropical moist and dry deciduous forests",
        "region": "India, Myanmar, Southeast Asia",
        "ecological_role": "Dominant canopy tree providing structural habitat for arboreal wildlife.",
        "importance": "Produces high-quality timber resistant to termites and rot.",
        "conservation": "Vulnerable (Overharvested in wild)",
        "conserved": True,
        "estimated_population": "N/A",
        "diet": "Photosynthetic",
        "threats": "Illegal logging, deforestation, and forest fires.",
        "facts": "Teak leaves produce a red dye when crushed and contain high silica content that preserves the wood.",
    },

    "Sal Tree": {
        "scientific_name": "Shorea robusta",
        "type": "Plant / Tree",
        "family": "Dipterocarpaceae",
        "habitat": "Subtropical and moist deciduous forests of South Asia",
        "region": "Indian Subcontinent (India, Nepal, Bangladesh)",
        "ecological_role": "Primary canopy builder, critical for watershed regulation and soil conservation.",
        "importance": "Seeds yield sal butter used in food and cosmetics; timber used for railway sleepers.",
        "conservation": "Least Concern (Widespread)",
        "conserved": False,
        "estimated_population": "N/A",
        "diet": "Photosynthetic",
        "threats": "Forest fragmentation and climate-induced monsoonal shifts.",
        "facts": "Sal trees are deciduous in dry seasons and drop their leaves just before new leaves emerge.",
    },

    "Peepal": {
        "scientific_name": "Ficus religiosa",
        "type": "Plant / Tree",
        "family": "Moraceae",
        "habitat": "Tropical and subtropical forests, temples, and roadsides",
        "region": "India, South Asia, Southeast Asia",
        "ecological_role": "Produces oxygen 24 hours a day including at night via Crassulacean metabolism.",
        "importance": "Sacred tree in Hinduism, Buddhism, and Jainism; significant air purifier.",
        "conservation": "Least Concern (Widespread)",
        "conserved": True,
        "estimated_population": "N/A",
        "diet": "Photosynthetic",
        "threats": "Urban development and road widening projects.",
        "facts": "The Peepal tree is one of the few trees that releases oxygen both day and night.",
    },

    "Mango": {
        "scientific_name": "Mangifera indica",
        "type": "Plant / Tree",
        "family": "Anacardiaceae",
        "habitat": "Tropical and subtropical lowland forests and orchards",
        "region": "India, South Asia (originated in northeastern India)",
        "ecological_role": "Provides food and habitat for birds, bats, and insects; stabilizes soil.",
        "importance": "National fruit of India; major commercial fruit crop worldwide.",
        "conservation": "Least Concern (Widespread)",
        "conserved": False,
        "estimated_population": "N/A",
        "diet": "Photosynthetic",
        "threats": "Anthracnose fungal disease and unsustainable monoculture farming.",
        "facts": "Mango trees can live for over 300 years and still produce fruit.",
    },

    "Coconut Palm": {
        "scientific_name": "Cocos nucifera",
        "type": "Plant / Palm Tree",
        "family": "Arecaceae",
        "habitat": "Tropical coastal regions, sandy soils, and island ecosystems",
        "region": "Tropical coastlines worldwide (India, Southeast Asia, Pacific Islands)",
        "ecological_role": "Coastal erosion prevention and habitat for numerous invertebrate species.",
        "importance": "Called the 'Tree of Life' — every part is used for food, shelter, and industry.",
        "conservation": "Least Concern (Widespread)",
        "conserved": False,
        "estimated_population": "N/A",
        "diet": "Photosynthetic",
        "threats": "Lethal yellowing disease and rising sea levels.",
        "facts": "Coconuts can float for months in seawater and germinate on distant shores, aiding natural dispersal.",
    },

    "Bamboo": {
        "scientific_name": "Bambusoideae (subfamily)",
        "type": "Plant / Grass-Tree",
        "family": "Poaceae",
        "habitat": "Tropical and temperate forests, river banks, and hillsides",
        "region": "Asia (India, China, Southeast Asia), Africa, South America",
        "ecological_role": "Rapid carbon sequestration; prevents soil erosion on slopes.",
        "importance": "Fastest growing plant on Earth; used in construction, paper, textiles, and food.",
        "conservation": "Least Concern (Widespread)",
        "conserved": False,
        "estimated_population": "N/A",
        "diet": "Photosynthetic",
        "threats": "Over-harvesting, habitat loss, and gregarious flowering events.",
        "facts": "Some bamboo species can grow up to 91 cm (36 inches) per day under optimal conditions.",
    },

    "Eucalyptus": {
        "scientific_name": "Eucalyptus globulus",
        "type": "Plant / Tree",
        "family": "Myrtaceae",
        "habitat": "Temperate and tropical forests, plantations",
        "region": "Australia, Tasmania",
        "ecological_role": "Provides essential oils with antiseptic properties; supports koala populations.",
        "importance": "Major source of essential oils, paper pulp, and timber worldwide.",
        "conservation": "Least Concern (Widespread)",
        "conserved": False,
        "estimated_population": "N/A",
        "diet": "Photosynthetic",
        "threats": "Highly flammable; prone to catastrophic wildfire damage.",
        "facts": "Eucalyptus oil is a natural insect repellent and has antimicrobial properties.",
    },

    "Pine": {
        "scientific_name": "Pinus (genus)",
        "type": "Plant / Coniferous Tree",
        "family": "Pinaceae",
        "habitat": "Temperate and boreal mountain forests worldwide",
        "region": "Northern Hemisphere (North America, Europe, Asia)",
        "ecological_role": "Pioneer species in forest succession; provides habitat for countless bird species.",
        "importance": "Major timber source; pine resin used in turpentine and rosin production.",
        "conservation": "Least Concern (Widespread)",
        "conserved": False,
        "estimated_population": "N/A",
        "diet": "Photosynthetic",
        "threats": "Pine bark beetle infestations and climate-driven wildfire.",
        "facts": "The oldest known living organism is a bristlecone pine tree over 5,000 years old.",
    },

    "Oak": {
        "scientific_name": "Quercus (genus)",
        "type": "Plant / Tree",
        "family": "Fagaceae",
        "habitat": "Temperate deciduous and mixed forests",
        "region": "Northern Hemisphere (North America, Europe, East Asia)",
        "ecological_role": "Keystone species supporting over 500 insect species; acorns feed many mammals.",
        "importance": "Premium hardwood for furniture, barrels, and construction.",
        "conservation": "Least Concern (Widespread)",
        "conserved": False,
        "estimated_population": "N/A",
        "diet": "Photosynthetic",
        "threats": "Sudden oak death disease and climate change.",
        "facts": "A single oak tree can produce up to 70,000 acorns per year.",
    },

    "Willow": {
        "scientific_name": "Salix (genus)",
        "type": "Plant / Tree",
        "family": "Salicaceae",
        "habitat": "Wetlands, river banks, and temperate floodplains",
        "region": "Northern Hemisphere (Europe, Asia, North America)",
        "ecological_role": "Prevents riverbank erosion; roots filter water pollutants.",
        "importance": "Bark contains salicin, the natural precursor to aspirin.",
        "conservation": "Least Concern (Widespread)",
        "conserved": False,
        "estimated_population": "N/A",
        "diet": "Photosynthetic",
        "threats": "Loss of wetland habitats and invasive pest species.",
        "facts": "Willow bark was used as pain relief medicine for over 3,500 years before aspirin was synthesized.",
    },

    "Maple": {
        "scientific_name": "Acer (genus)",
        "type": "Plant / Tree",
        "family": "Sapindaceae",
        "habitat": "Temperate forests of North America, Europe, and East Asia",
        "region": "North America, Europe, East Asia (Japan, China)",
        "ecological_role": "Provides autumn leaf litter that enriches forest soil ecosystems.",
        "importance": "Source of maple syrup; valued ornamental and timber tree.",
        "conservation": "Least Concern (Widespread)",
        "conserved": False,
        "estimated_population": "N/A",
        "diet": "Photosynthetic",
        "threats": "Asian longhorned beetle infestations and acid rain.",
        "facts": "It takes approximately 40 liters of maple sap to produce 1 liter of maple syrup.",
    },

    "Hibiscus": {
        "scientific_name": "Hibiscus rosa-sinensis",
        "type": "Plant / Flowering Shrub",
        "family": "Malvaceae",
        "habitat": "Warm tropical and subtropical gardens and secondary forests",
        "region": "Tropical and subtropical regions worldwide (India, China, Pacific Islands)",
        "ecological_role": "Attracts key pollinators including hummingbirds, butterflies, and bees.",
        "importance": "Widely cultivated for ornamental beauty and herbal teas rich in Vitamin C.",
        "conservation": "Least Concern (Widespread)",
        "conserved": False,
        "estimated_population": "N/A",
        "diet": "Photosynthetic",
        "threats": "Aphid infestations and frost exposure.",
        "facts": "Hibiscus flowers contain natural pH indicators that change color in acidic or basic solutions.",
    },

    "Sunflower": {
        "scientific_name": "Helianthus annuus",
        "type": "Plant / Annual Flower",
        "family": "Asteraceae",
        "habitat": "Open sunny fields, grasslands, and agricultural regions",
        "region": "North America (originated in central USA and Mexico)",
        "ecological_role": "Provides pollen for honeybees and nutritious seeds for wild birds.",
        "importance": "Major agricultural crop for edible sunflower oil and seeds.",
        "conservation": "Least Concern (Widespread)",
        "conserved": False,
        "estimated_population": "N/A",
        "diet": "Photosynthetic",
        "threats": "Drought stress and bird foraging in commercial crops.",
        "facts": "Young sunflowers exhibit heliotropism, tracking the sun from east to west across the sky every day.",
    },

    "Rose": {
        "scientific_name": "Rosa (genus)",
        "type": "Plant / Flowering Shrub",
        "family": "Rosaceae",
        "habitat": "Temperate gardens, woodlands, and cultivated landscapes worldwide",
        "region": "Asia, Europe, North America (originated in China and Persia)",
        "ecological_role": "Supports pollinator networks including bees, butterflies, and hoverflies.",
        "importance": "The world's most popular ornamental flower; source of rose oil and rosewater.",
        "conservation": "Least Concern (Widespread)",
        "conserved": False,
        "estimated_population": "N/A",
        "diet": "Photosynthetic",
        "threats": "Black spot fungus, aphids, and powdery mildew.",
        "facts": "The oldest known living rose bush is over 1,000 years old and grows on a cathedral wall in Germany.",
    },

    "Jasmine": {
        "scientific_name": "Jasminum (genus)",
        "type": "Plant / Flowering Vine/Shrub",
        "family": "Oleaceae",
        "habitat": "Tropical and warm temperate gardens and hedgerows",
        "region": "South Asia, Southeast Asia (India, Pakistan, Iran)",
        "ecological_role": "Night-blooming species attract moths and nocturnal pollinators.",
        "importance": "Prized for perfumery; jasmine oil is one of the most expensive essential oils.",
        "conservation": "Least Concern (Widespread)",
        "conserved": False,
        "estimated_population": "N/A",
        "diet": "Photosynthetic",
        "threats": "Jasmine bud worm and cold damage.",
        "facts": "Jasmine flowers release their strongest fragrance at night to attract pollinating moths.",
    },

    "Marigold": {
        "scientific_name": "Tagetes (genus)",
        "type": "Plant / Annual Flower",
        "family": "Asteraceae",
        "habitat": "Gardens, fields, and roadsides in tropical and temperate zones",
        "region": "Central America, Mexico, India (widely cultivated)",
        "ecological_role": "Natural pest repellent; roots release thiophenes that deter nematodes.",
        "importance": "Used extensively in festivals, garlands, and as a natural dye source.",
        "conservation": "Least Concern (Widespread)",
        "conserved": False,
        "estimated_population": "N/A",
        "diet": "Photosynthetic",
        "threats": "Spider mites and powdery mildew.",
        "facts": "Marigold roots exude chemicals that repel harmful soil nematodes, making them excellent companion plants.",
    },

    "Lavender": {
        "scientific_name": "Lavandula (genus)",
        "type": "Plant / Aromatic Shrub",
        "family": "Lamiaceae",
        "habitat": "Mediterranean scrubland, rocky slopes, and dry temperate gardens",
        "region": "Mediterranean region (France, Spain, Italy)",
        "ecological_role": "Major nectar source for honeybees and wild pollinators.",
        "importance": "Essential oil used in aromatherapy, perfumery, and medicinal applications.",
        "conservation": "Least Concern (Widespread)",
        "conserved": False,
        "estimated_population": "N/A",
        "diet": "Photosynthetic",
        "threats": "Root rot in humid climates and Cecidomyiid gall midge.",
        "facts": "Lavender fields in Provence, France cover over 20,000 hectares and support local bee populations.",
    },

    "Orchid": {
        "scientific_name": "Orchidaceae (family)",
        "type": "Plant / Epiphytic Flower",
        "family": "Orchidaceae",
        "habitat": "Tropical rainforest canopy, temperate woodlands, and montane cloud forests",
        "region": "Tropical regions worldwide (Southeast Asia, Central and South America)",
        "ecological_role": "Highly specialized pollinator relationships; some mimic insects to attract pollinators.",
        "importance": "Largest family of flowering plants with over 28,000 species; major horticultural industry.",
        "conservation": "Vulnerable (Some species Endangered)",
        "conserved": True,
        "estimated_population": "N/A",
        "diet": "Photosynthetic / Some mycoheterotrophic",
        "threats": "Illegal collection, habitat destruction, and climate change.",
        "facts": "Vanilla flavoring comes from the seed pods of the Vanilla orchid, the only commercially grown orchid for food.",
    },

    "Bougainvillea": {
        "scientific_name": "Bougainvillea (genus)",
        "type": "Plant / Flowering Vine",
        "family": "Nyctaginaceae",
        "habitat": "Tropical and subtropical gardens, walls, and trellises",
        "region": "South America (Brazil), widely cultivated in tropical regions",
        "ecological_role": "Provides nectar for butterflies and hummingbirds; thorns deter herbivores.",
        "importance": "Popular ornamental plant known for vibrant paper-like bracts.",
        "conservation": "Least Concern (Widespread)",
        "conserved": False,
        "estimated_population": "N/A",
        "diet": "Photosynthetic",
        "threats": "Frost damage and leaf miners.",
        "facts": "The colorful 'petals' of bougainvillea are actually modified leaves (bracts); the true flowers are tiny and white.",
    },

    "Daisy": {
        "scientific_name": "Bellis perennis",
        "type": "Plant / Perennial Flower",
        "family": "Asteraceae",
        "habitat": "Grasslands, lawns, and meadows across Europe and temperate zones",
        "region": "Europe, North America",
        "ecological_role": "Early-season nectar source for emerging bees and beneficial insects.",
        "importance": "Symbol of innocence; used in traditional herbal medicine.",
        "conservation": "Least Concern (Widespread)",
        "conserved": False,
        "estimated_population": "N/A",
        "diet": "Photosynthetic",
        "threats": "Herbicide use on lawns and habitat fragmentation.",
        "facts": "The name 'daisy' comes from 'day's eye' because the flower opens at dawn and closes at dusk.",
    },

    "Lily": {
        "scientific_name": "Lilium (genus)",
        "type": "Plant / Bulbous Flower",
        "family": "Liliaceae",
        "habitat": "Temperate and mountain forests, gardens, and wetland edges",
        "region": "Northern Hemisphere (Europe, Asia, North America)",
        "ecological_role": "Attracts specialized pollinators including large butterflies and hawk moths.",
        "importance": "Major cut flower industry; symbolically important in many cultures.",
        "conservation": "Least Concern (Some species Near Threatened)",
        "conserved": False,
        "estimated_population": "N/A",
        "diet": "Photosynthetic",
        "threats": "Lily beetle, bulb rot, and habitat loss.",
        "facts": "Some lily species can grow over 2 meters tall and produce flowers with a diameter exceeding 15 cm.",
    },

    "Chrysanthemum": {
        "scientific_name": "Chrysanthemum (genus)",
        "type": "Plant / Perennial Flower",
        "family": "Asteraceae",
        "habitat": "Temperate gardens and cultivated landscapes of East Asia and Europe",
        "region": "East Asia (China, Japan)",
        "ecological_role": "Late-season pollen source when few other flowers remain.",
        "importance": "Contains pyrethrin, a natural insecticide; culturally revered in Japan and China.",
        "conservation": "Least Concern (Widespread)",
        "conserved": False,
        "estimated_population": "N/A",
        "diet": "Photosynthetic",
        "threats": "Aphids, leaf miners, and white rust fungus.",
        "facts": "Chrysanthemum pyrethrin extract is the basis of many commercial organic insecticides used worldwide.",
    },

    "Tulsi (Holy Basil)": {
        "scientific_name": "Ocimum sanctum",
        "type": "Plant / Aromatic Herb",
        "family": "Lamiaceae",
        "habitat": "Tropical plains, river banks, and traditional gardens",
        "region": "India, South Asia (sacred plant of India)",
        "ecological_role": "Natural insect repellant and oxygen supplier.",
        "importance": "Revered in Ayurvedic medicine for respiratory health and immunity.",
        "conservation": "Least Concern (Widespread)",
        "conserved": True,
        "estimated_population": "N/A",
        "diet": "Photosynthetic",
        "threats": "Fungal wilt and cold temperatures.",
        "facts": "Tulsi leaves emit essential oils like eugenol that deter mosquitoes and airborne bacteria.",
    },

    "Mint": {
        "scientific_name": "Mentha (genus)",
        "type": "Plant / Aromatic Herb",
        "family": "Lamiaceae",
        "habitat": "Moist meadows, stream banks, and cultivated herb gardens",
        "region": "Europe, Asia, North America (worldwide cultivation)",
        "ecological_role": "Attracts beneficial predatory insects; repels garden pests.",
        "importance": "Used in cuisine, medicine, cosmetics, and as a flavoring agent worldwide.",
        "conservation": "Least Concern (Widespread)",
        "conserved": False,
        "estimated_population": "N/A",
        "diet": "Photosynthetic",
        "threats": "Mint rust fungus and aggressive invasive spreading.",
        "facts": "Mint is so vigorous that it can take over an entire garden if not contained in pots.",
    },

    "Coriander (Cilantro)": {
        "scientific_name": "Coriandrum sativum",
        "type": "Plant / Culinary Herb",
        "family": "Apiaceae",
        "habitat": "Cultivated gardens and fields in temperate and tropical regions",
        "region": "Mediterranean, Southern Europe, Western Asia, India",
        "ecological_role": "Flowers attract hoverflies and parasitic wasps that control aphid populations.",
        "importance": "One of the most widely used culinary herbs globally; seeds used as spice.",
        "conservation": "Least Concern (Widespread)",
        "conserved": False,
        "estimated_population": "N/A",
        "diet": "Photosynthetic",
        "threats": "Bolting in hot weather and bacterial leaf spot.",
        "facts": "Whether coriander tastes pleasant or like soap is genetically determined by olfactory receptor genes.",
    },

    "Fern": {
        "scientific_name": "Polypodiopsida (class)",
        "type": "Plant / Pteridophyte",
        "family": "Various fern families",
        "habitat": "Tropical and temperate forest understory, rock crevices, and wetlands",
        "region": "Tropical and temperate forests worldwide",
        "ecological_role": "Ground cover preventing erosion; provides microhabitat for invertebrates.",
        "importance": "Among the oldest land plants; important in horticulture and traditional medicine.",
        "conservation": "Least Concern (Some species Endangered)",
        "conserved": False,
        "estimated_population": "N/A",
        "diet": "Photosynthetic",
        "threats": "Deforestation, invasive species, and climate change.",
        "facts": "Ferns are over 360 million years old — they existed before dinosaurs and flowering plants.",
    },

    "Aloe Vera": {
        "scientific_name": "Aloe barbadensis Miller",
        "type": "Plant / Succulent",
        "family": "Asphodelaceae",
        "habitat": "Arid, semi-arid, and coastal tropical zones",
        "region": "Arabian Peninsula, North Africa, India (widely naturalized)",
        "ecological_role": "Prevents soil erosion in arid landscapes and stores moisture.",
        "importance": "Extensively processed for skin healing, cosmetics, and medicinal aloe gel.",
        "conservation": "Least Concern (Widespread)",
        "conserved": False,
        "estimated_population": "N/A",
        "diet": "Photosynthetic (CAM Metabolism)",
        "threats": "Root rot from overwatering and freezing temperatures.",
        "facts": "Aloe Vera uses Crassulacean Acid Metabolism (CAM) to absorb carbon dioxide at night to conserve water.",
    },

    "Cactus": {
        "scientific_name": "Cactaceae (family)",
        "type": "Plant / Succulent",
        "family": "Cactaceae",
        "habitat": "Deserts, arid scrublands, and dry rocky hillsides of the Americas",
        "region": "Americas (North and South America, Mexico)",
        "ecological_role": "Critical water source for desert wildlife; provides nesting sites for birds.",
        "importance": "Adapted to extreme drought; some species produce edible fruit (prickly pear).",
        "conservation": "Vulnerable (Varies by species)",
        "conserved": True,
        "estimated_population": "N/A",
        "diet": "Photosynthetic (CAM Metabolism)",
        "threats": "Illegal collection, habitat conversion, and climate change.",
        "facts": "The Saguaro cactus can live for 200 years, grow 12 meters tall, and store over 750 liters of water.",
    },

    "Jade Plant": {
        "scientific_name": "Crassula ovata",
        "type": "Plant / Succulent",
        "family": "Crassulaceae",
        "habitat": "Rocky hillsides and dry grasslands of South Africa and Mozambique",
        "region": "South Africa, Mozambique",
        "ecological_role": "Stores water in leaves; supports pollinators when flowering in winter.",
        "importance": "Popular houseplant symbolizing prosperity; easy to propagate from leaves.",
        "conservation": "Least Concern (Widespread)",
        "conserved": False,
        "estimated_population": "N/A",
        "diet": "Photosynthetic (CAM Metabolism)",
        "threats": "Root rot, mealybugs, and frost damage.",
        "facts": "Jade plants can live for over 100 years and some bonsai jade specimens are passed down generations.",
    },

    # ==================== AQUATIC PLANTS ====================

    "Lotus": {
        "scientific_name": "Nelumbo nucifera",
        "type": "Plant / Aquatic",
        "family": "Nelumbonaceae",
        "habitat": "Freshwater ponds, lakes, marshes, and river deltas",
        "region": "India, East Asia, Australia (National Flower of India)",
        "ecological_role": "Oxygenates water bodies; provides shade, nesting cover, and shelter for aquatic animals.",
        "importance": "National flower of India; sacred in Eastern philosophies; edible tubers and seeds.",
        "conservation": "Least Concern (Widespread)",
        "conserved": True,
        "estimated_population": "N/A",
        "diet": "Photosynthetic (aquatic)",
        "threats": "Water pollution, wetland destruction, and heavy metal bioaccumulation.",
        "facts": "Lotus leaves are superhydrophobic; water rolls off them in perfect spheres, washing off dirt (Lotus Effect).",
    },

    "Water Lily": {
        "scientific_name": "Nymphaea (genus)",
        "type": "Plant / Aquatic",
        "family": "Nymphaeaceae",
        "habitat": "Shallow, quiet freshwater bodies like ponds, lake edges, and slow-moving streams",
        "region": "Tropical and temperate regions worldwide",
        "ecological_role": "Provides shelter for aquatic insects and fish; leaves limit algae growth by blocking sunlight.",
        "importance": "Extensively cultivated as an ornamental aquatic plant; symbolic in Egyptian art.",
        "conservation": "Least Concern (Widespread)",
        "conserved": False,
        "estimated_population": "N/A",
        "diet": "Photosynthetic (aquatic)",
        "threats": "Wetland reclamation, herbicide runoff, and invasive plant competition.",
        "facts": "Water lily flowers float on the surface, opening in the daytime and closing tightly at night.",
    },

    "Water Hyacinth": {
        "scientific_name": "Eichhornia crassipes",
        "type": "Plant / Aquatic",
        "family": "Pontederiaceae",
        "habitat": "Tropical and subtropical freshwater lakes, rivers, and reservoirs",
        "region": "South America (Amazon Basin), invasive worldwide",
        "ecological_role": "Filters heavy metals and excess nutrients from contaminated water bodies.",
        "importance": "Among the most aggressive invasive species; clogs waterways, blocking navigation and light.",
        "conservation": "Invasive / Least Concern",
        "conserved": False,
        "estimated_population": "N/A",
        "diet": "Photosynthetic (aquatic)",
        "threats": "Actively targeted for biological control and mechanical removal programs.",
        "facts": "A single water hyacinth colony can double in size in under two weeks, creating massive floating mats.",
    },

    "Duckweed": {
        "scientific_name": "Lemnoideae (subfamily)",
        "type": "Plant / Aquatic",
        "family": "Araceae",
        "habitat": "Still or slow-moving freshwater ponds, wetlands, and quiet backwaters",
        "region": "Freshwater habitats worldwide",
        "ecological_role": "High-protein food source for waterfowl, fish, and turtles; prevents mosquito breeding by covering surface.",
        "importance": "Used in wastewater treatment and researched as a high-yield biofuel source.",
        "conservation": "Least Concern (Widespread)",
        "conserved": False,
        "estimated_population": "N/A",
        "diet": "Photosynthetic (aquatic)",
        "threats": "Chemical contamination and eutrophication.",
        "facts": "Duckweed is the smallest known flowering plant in the world, consisting of tiny floating green fronds.",
    },

    "Eelgrass": {
        "scientific_name": "Zostera marina",
        "type": "Plant / Aquatic",
        "family": "Zosteraceae",
        "habitat": "Shallow coastal estuaries, lagoons, and sandy or muddy marine environments",
        "region": "North Atlantic, North Pacific coastal waters",
        "ecological_role": "Acts as a primary nursery habitat for juvenile fish, crabs, and shellfish; buffers shoreline erosion.",
        "importance": "Crucial carbon-sink and foundation species for marine ecosystem health.",
        "conservation": "Least Concern (Degrading locally)",
        "conserved": True,
        "estimated_population": "N/A",
        "diet": "Photosynthetic (marine)",
        "threats": "Coastal development, agricultural runoff, dredging, and warming ocean temperatures.",
        "facts": "Eelgrass is a true marine angiosperm, meaning it flowers and pollinates entirely underwater.",
    },

    "Hydrilla": {
        "scientific_name": "Hydrilla verticillata",
        "type": "Plant / Aquatic",
        "family": "Hydrocharitaceae",
        "habitat": "Ponds, lakes, rivers, and estuaries across tropical and temperate zones",
        "region": "Asia (India, Southeast Asia), Africa, Australia",
        "ecological_role": "Provides cover for small fish, though it aggressively outcompetes native aquatic flora.",
        "importance": "Noxious aquatic weed that creates dense underwater columns, hindering boating and fishing.",
        "conservation": "Invasive / Least Concern",
        "conserved": False,
        "estimated_population": "N/A",
        "diet": "Photosynthetic (aquatic)",
        "threats": "Active eradication via chemical, mechanical, and biological controls.",
        "facts": "Hydrilla is extremely resilient; a tiny plant fragment can regenerate into a full plant colony.",
    },

    "Coontail": {
        "scientific_name": "Ceratophyllum demersum",
        "type": "Plant / Aquatic",
        "family": "Ceratophyllaceae",
        "habitat": "Still or slow-moving freshwater ponds, lakes, and marshes worldwide",
        "region": "Freshwater habitats worldwide (all continents except Antarctica)",
        "ecological_role": "Produces oxygen; provides vital spawning grounds and cover for game fish and amphibians.",
        "importance": "Used widely in home aquariums to control algae and clarify water.",
        "conservation": "Least Concern (Widespread)",
        "conserved": False,
        "estimated_population": "N/A",
        "diet": "Photosynthetic (aquatic)",
        "threats": "High herbicide pollution and extreme dredging.",
        "facts": "Coontail has no true roots; it either floats freely near the surface or anchor-drifts using modified leaves.",
    },

    # ==================== LAND ANIMALS (MAMMALS) ====================

    "Bengal Tiger": {
        "scientific_name": "Panthera tigris tigris",
        "type": "Animal / Mammal",
        "family": "Felidae",
        "habitat": "Forests, grasslands, wetlands, and mangrove ecosystems of India and Nepal",
        "region": "India, Bangladesh, Nepal (Indian Subcontinent)",
        "ecological_role": "Apex predator that regulates prey populations and maintains ecosystem health.",
        "importance": "A flagship species for global forest and biodiversity conservation efforts.",
        "conservation": "Endangered",
        "conserved": True,
        "estimated_population": "~3,500 - 4,000 in the wild",
        "diet": "Carnivorous (Deer, Wild Boar, Gaur, Antelope)",
        "threats": "Poaching for skin/bones, habitat fragmentation, and human-wildlife conflict.",
        "facts": "Each tiger's stripe pattern is completely unique, acting like a human fingerprint for identification.",
    },

    "Indian Elephant": {
        "scientific_name": "Elephas maximus indicus",
        "type": "Animal / Mammal",
        "family": "Elephantidae",
        "habitat": "Tropical moist deciduous, dry forests, grasslands, and riverine corridors",
        "region": "India, Sri Lanka, Southeast Asia",
        "ecological_role": "Ecosystem engineer that opens canopy paths, digs water holes, and disperses seeds.",
        "importance": "Cultural icon of South Asia and a keystone species critical for forest rejuvenation.",
        "conservation": "Endangered",
        "conserved": True,
        "estimated_population": "~20,000 - 25,000 in the wild",
        "diet": "Herbivorous (Grasses, Bark, Roots, Leaves, Wild Fruits)",
        "threats": "Habitat fragmentation, linear infrastructure, ivory poaching, and conflict with farmers.",
        "facts": "An adult elephant can consume up to 150 kg of vegetation and 100 liters of water daily.",
    },

    "Indian Leopard": {
        "scientific_name": "Panthera pardus fusca",
        "type": "Animal / Mammal",
        "family": "Felidae",
        "habitat": "Dense tropical forests, rocky scrublands, and agricultural forest boundaries",
        "region": "India, South Asia, Southeast Asia",
        "ecological_role": "Top-tier carnivore regulating mid-sized herbivores and small mammals.",
        "importance": "Extremely adaptable predator that indicator-marks forest health.",
        "conservation": "Vulnerable",
        "conserved": True,
        "estimated_population": "~12,000 - 14,000 in India",
        "diet": "Carnivorous (Spotted Deer, Monkeys, Rodents, Hares)",
        "threats": "Illegal wildlife trade, agricultural conversion, and retaliatory poisoning.",
        "facts": "Leopards are exceptional climbers capable of carrying prey larger than themselves up into tree limbs.",
    },

    "Asiatic Lion": {
        "scientific_name": "Panthera leo persica",
        "type": "Animal / Mammal",
        "family": "Felidae",
        "habitat": "Dry deciduous forests and open teak grasslands of Gir National Park, India",
        "region": "India (Gir Forest, Gujarat — only wild population)",
        "ecological_role": "Apex predator structuring open forest food webs.",
        "importance": "The last surviving population of lions outside of the African continent.",
        "conservation": "Endangered",
        "conserved": True,
        "estimated_population": "~674 individuals in the wild",
        "diet": "Carnivorous (Chital, Sambar, Nilgai, Wild Boar)",
        "threats": "Diseases (e.g., Canine Distemper), open farm wells, and genetic bottleneck vulnerability.",
        "facts": "Asiatic lions are slightly smaller than African lions and possess a distinctive fold of skin running along their belly.",
    },

    "Wolf": {
        "scientific_name": "Canis lupus",
        "type": "Animal / Mammal",
        "family": "Canidae",
        "habitat": "Forests, tundras, grasslands, and dry desert plains worldwide",
        "region": "North America, Europe, Asia (Northern Hemisphere)",
        "ecological_role": "Apex pack hunter that creates trophic cascades, keeping herbivore populations moving to prevent overgrazing.",
        "importance": "Indicator of wild, unfragmented habitats; vital in ecosystem balance studies.",
        "conservation": "Least Concern (Subpopulations Endangered)",
        "conserved": True,
        "estimated_population": "~200,000 - 300,000 globally",
        "diet": "Carnivorous (Deer, Elk, Moose, Hares, Rodents)",
        "threats": "Government-sanctioned predator controls, habitat degradation, and hybridization with domestic dogs.",
        "facts": "Wolf packs communicate through complex vocalizations, body postures, and scent marking across vast territories.",
    },

    "Red Panda": {
        "scientific_name": "Ailurus fulgens",
        "type": "Animal / Mammal",
        "family": "Ailuridae",
        "habitat": "Temperate montane forests with bamboo understory in the Eastern Himalayas",
        "region": "Eastern Himalayas (India, Nepal, Bhutan, China, Myanmar)",
        "ecological_role": "Regulates bamboo density and acts as a key seed disperser.",
        "importance": "Flagship species representing the unique biodiversity of the Himalayan cloud forests.",
        "conservation": "Endangered",
        "conserved": True,
        "estimated_population": "Under 10,000 individuals globally",
        "diet": "Herbivorous (primarily Bamboo shoots and leaves, plus berries and eggs)",
        "threats": "Deforestation, bamboo flowering cycles (die-offs), and accidental snaring.",
        "facts": "Red pandas have a specialized, elongated wrist bone called a 'pseudo-thumb' to grip bamboo stems.",
    },

    "Spotted Deer": {
        "scientific_name": "Axis axis",
        "type": "Animal / Mammal",
        "family": "Cervidae",
        "habitat": "Deciduous and evergreen forests, riverine grasslands, and open woodlands",
        "region": "Indian Subcontinent (India, Sri Lanka, Nepal)",
        "ecological_role": "Major prey base for leopards and tigers; maintains grasslands via grazing.",
        "importance": "Crucial indicator species for forest prey density and ecosystem stability.",
        "conservation": "Least Concern (Widespread)",
        "conserved": False,
        "estimated_population": "Abundant (estimated over 1 million)",
        "diet": "Herbivorous (Fallen leaves, grasses, herbs, tree shoots)",
        "threats": "Feral dog predation, habitat loss, and competition with invasive weeds.",
        "facts": "Spotted deer (Chital) share a mutualistic relationship with Langur monkeys, grazing on leaves dropped by the monkeys.",
    },

    "Sloth Bear": {
        "scientific_name": "Melursus ursinus",
        "type": "Animal / Mammal",
        "family": "Ursidae",
        "habitat": "Dry forest scrublands, grasslands, and rocky forest outcrops of South Asia",
        "region": "Indian Subcontinent (India, Sri Lanka, Nepal)",
        "ecological_role": "Controls forest termite and ant populations; claws aerate soil when digging.",
        "importance": "Highly specialized insectivorous bear, crucial to underground insect regulation.",
        "conservation": "Vulnerable",
        "conserved": True,
        "estimated_population": "~10,000 - 20,000 in the wild",
        "diet": "Omnivorous (Termites, Ants, Honeycombs, Mahua flowers, wild fruits)",
        "threats": "Habitat destruction, poaching for bile/organs, and human-bear encounters.",
        "facts": "Sloth bears can close their nostrils at will, and they lack front incisor teeth, forming a natural straw to suck up termites.",
    },

    "Rhesus Macaque": {
        "scientific_name": "Macaca mulatta",
        "type": "Animal / Mammal",
        "family": "Cercopithecidae",
        "habitat": "Deciduous forests, urban cities, temples, and scrub forests",
        "region": "South and Central Asia (India, China, Afghanistan)",
        "ecological_role": "Disperses seeds of native trees; prey for large forest predators.",
        "importance": "Major species in biomedical research; highly integrated into human-occupied ecosystems.",
        "conservation": "Least Concern (Widespread)",
        "conserved": False,
        "estimated_population": "Over 5 million globally",
        "diet": "Omnivorous (Fruits, Seeds, Roots, Leaves, Insects, Human scraps)",
        "threats": "Urban control efforts, traffic collisions, and pesticide exposure.",
        "facts": "Rhesus macaques were the first monkeys in space, and the 'Rh' blood group factor is named after them.",
    },

    "Red Fox": {
        "scientific_name": "Vulpes vulpes",
        "type": "Animal / Mammal",
        "family": "Canidae",
        "habitat": "Forests, grasslands, deserts, mountains, and suburban areas worldwide",
        "region": "Northern Hemisphere (North America, Europe, Asia, North Africa)",
        "ecological_role": "Keeps rodent and insect populations in check.",
        "importance": "The most widely distributed wild carnivore on the planet.",
        "conservation": "Least Concern (Widespread)",
        "conserved": False,
        "estimated_population": "Over 2 million in the wild",
        "diet": "Omnivorous (Rodents, Rabbits, Insects, Berries, Birds)",
        "threats": "Fur trapping, sarcoptic mange outbreaks, and urban vehicle accidents.",
        "facts": "Red foxes use the Earth's magnetic field to hunt, pouncing on prey hidden deep beneath snow.",
    },

    "Giant Panda": {
        "scientific_name": "Ailuropoda melanoleuca",
        "type": "Animal / Mammal",
        "family": "Ursidae",
        "habitat": "Temperate bamboo forests in the mountainous regions of central China",
        "region": "China (Sichuan, Shaanxi, Gansu provinces)",
        "ecological_role": "Disperses bamboo seeds, helping forest renewal.",
        "importance": "Global symbol of wildlife conservation and biological preservation.",
        "conservation": "Vulnerable (Recovering)",
        "conserved": True,
        "estimated_population": "~1,860 in the wild",
        "diet": "Herbivorous (99% Bamboo, occasionally small rodents)",
        "threats": "Habitat fragmentation, bamboo logging, and low reproductive success.",
        "facts": "A Giant Panda spends up to 14 hours a day eating up to 12.5 kg of bamboo to meet its nutritional needs.",
    },

    "Cheetah": {
        "scientific_name": "Acinonyx jubatus",
        "type": "Animal / Mammal",
        "family": "Felidae",
        "habitat": "Savannas, open dry grasslands, and scrub forests of Africa and Iran",
        "region": "Africa (Sub-Saharan), Iran (small population)",
        "ecological_role": "High-speed pursuit predator regulating grassland ungulates.",
        "importance": "The fastest land mammal on Earth; crucial to grassland biodiversity.",
        "conservation": "Vulnerable",
        "conserved": True,
        "estimated_population": "~7,100 in the wild",
        "diet": "Carnivorous (Gazelles, Impalas, Hares, Wildebeest calves)",
        "threats": "Loss of habitat, genetic homogeneity, and illegal pet trade cub smuggling.",
        "facts": "A cheetah can accelerate from 0 to 97 km/h (60 mph) in just 3 seconds, though its high-speed runs exhaust it quickly.",
    },

    "Grizzly Bear": {
        "scientific_name": "Ursus arctos horribilis",
        "type": "Animal / Mammal",
        "family": "Ursidae",
        "habitat": "Temperate forests, alpine meadows, valleys, and coastal wetlands of North America",
        "region": "North America (USA — Alaska, Canada)",
        "ecological_role": "Spreads seeds, excavates soil for bulbs, and distributes marine nutrients from salmon feeding.",
        "importance": "Keystone predator and indicator of healthy, unfragmented wilderness.",
        "conservation": "Vulnerable (Threatened in USA)",
        "conserved": True,
        "estimated_population": "~55,000 in North America",
        "diet": "Omnivorous (Berries, Salmon, Roots, Insects, Large Ungulates)",
        "threats": "Human encroachment, logging, mining, and road development.",
        "facts": "Grizzly bears go through hyperphagia in autumn, gaining up to 1.5 kg of fat daily before hibernation.",
    },

    "Red Kangaroo": {
        "scientific_name": "Osphranter rufus",
        "type": "Animal / Mammal",
        "family": "Macropodidae",
        "habitat": "Arid and semi-arid grasslands, shrublands, and deserts of Australia",
        "region": "Australia (arid and semi-arid interior)",
        "ecological_role": "Major grazer that shapes vegetation structure and acts as prey for dingoes.",
        "importance": "Largest native land mammal in Australia; emblem of Australian ecology.",
        "conservation": "Least Concern (Widespread)",
        "conserved": False,
        "estimated_population": "~11 million in Australia",
        "diet": "Herbivorous (Dry grasses, shrubs, foliage)",
        "threats": "Drought, commercial culling, and wild dog predation.",
        "facts": "A red kangaroo cannot walk backward, and its hopping motion is highly energy-efficient at high speeds.",
    },

    "Platypus": {
        "scientific_name": "Ornithorhynchus anatinus",
        "type": "Animal / Mammal",
        "family": "Ornithorhynchidae",
        "habitat": "Freshwater rivers, creeks, and lakes in eastern Australia",
        "region": "Eastern Australia, Tasmania",
        "ecological_role": "Benthic predator regulating freshwater macroinvertebrates.",
        "importance": "One of only five surviving species of monotremes (egg-laying mammals).",
        "conservation": "Near Threatened",
        "conserved": True,
        "estimated_population": "~30,000 - 50,000 in the wild",
        "diet": "Carnivorous (Benthic worms, insect larvae, freshwater shrimp)",
        "threats": "River damming, water pollution, land clearing, and gill net entanglement.",
        "facts": "The platypus has electroreceptors in its bill to detect electric fields generated by the muscles of its prey.",
    },

    # ==================== BIRDS ====================

    "Indian Peafowl": {
        "scientific_name": "Pavo cristatus",
        "type": "Animal / Bird",
        "family": "Phasianidae",
        "habitat": "Dry deciduous forests, open woodlands, scrublands, and rural farms",
        "region": "India, Sri Lanka, South Asia (National Bird of India)",
        "ecological_role": "Controls snake, scorpion, and insect populations.",
        "importance": "National bird of India; protected by strict wildlife legislation.",
        "conservation": "Least Concern (Widespread)",
        "conserved": True,
        "estimated_population": "Over 100,000 in South Asia",
        "diet": "Omnivorous (Seeds, fruits, insects, small reptiles, crop shoots)",
        "threats": "Poaching for feathers and accidental pesticide poisoning.",
        "facts": "Male peacocks shake their massive trains to create low-frequency infrasound that humans cannot hear.",
    },

    "Rose-ringed Parakeet": {
        "scientific_name": "Psittacula krameri",
        "type": "Animal / Bird",
        "family": "Psittacidae",
        "habitat": "Lowland forests, urban parks, farmland, and city suburbs",
        "region": "India, Sub-Saharan Africa, South Asia",
        "ecological_role": "Seed predator and disperser; tree hollow nester.",
        "importance": "Highly successful colonizer; popular globally in the pet trade.",
        "conservation": "Least Concern (Abundant)",
        "conserved": False,
        "estimated_population": "Abundant (estimated over 10 million)",
        "diet": "Herbivorous (Fruits, cereal grains, seeds, flower buds, nectar)",
        "threats": "Persecution as agricultural crop pests.",
        "facts": "Rose-ringed parakeets have established feral populations in cities worldwide, from London to Tokyo.",
    },

    "Golden Eagle": {
        "scientific_name": "Aquila chrysaetos",
        "type": "Animal / Bird",
        "family": "Accipitridae",
        "habitat": "High mountainous cliffs, open moorlands, and coniferous forests",
        "region": "Northern Hemisphere (North America, Europe, Asia, North Africa)",
        "ecological_role": "Apex avian predator keeping small mammal populations stable.",
        "importance": "One of the best-known birds of prey; emblem of power and freedom.",
        "conservation": "Least Concern (Widespread)",
        "conserved": True,
        "estimated_population": "~250,000 globally",
        "diet": "Carnivorous (Hares, marmots, ground squirrels, young deer, birds)",
        "threats": "Wind turbine collisions, lead poisoning from ammunition, and habitat loss.",
        "facts": "Golden eagles can dive at speeds exceeding 240 km/h (150 mph) when chasing prey.",
    },

    "Common Kingfisher": {
        "scientific_name": "Alcedo atthis",
        "type": "Animal / Bird",
        "family": "Alcedinidae",
        "habitat": "Slow-flowing streams, rivers, freshwater lakes, and coastal bays",
        "region": "Europe, Asia, North Africa",
        "ecological_role": "Indicator of clean water systems; regulates small fish and aquatic insect numbers.",
        "importance": "Iconic freshwater hunter; inspired the nose design of the Japanese Shinkansen bullet train.",
        "conservation": "Least Concern (Widespread)",
        "conserved": False,
        "estimated_population": "~1.5 - 3 million globally",
        "diet": "Carnivorous (Minnows, sticklebacks, water beetles, tadpoles)",
        "threats": "Water pollution, riverbank concrete walling, and severe winter freezes.",
        "facts": "The common kingfisher has eyes that adjust to refraction, allowing it to locate fish accurately from above water.",
    },

    "Barn Owl": {
        "scientific_name": "Tyto alba",
        "type": "Animal / Bird",
        "family": "Tytonidae",
        "habitat": "Agricultural fields, grasslands, forest edges, and barns/abandoned structures",
        "region": "Worldwide (all continents except Antarctica)",
        "ecological_role": "Nocturnal rodent controller; a single family eats thousands of rats annually.",
        "importance": "Natural pest control agent highly valued by agricultural communities.",
        "conservation": "Least Concern (Widespread)",
        "conserved": False,
        "estimated_population": "~2 - 4 million globally",
        "diet": "Carnivorous (Volles, shrews, field mice, rats)",
        "threats": "Secondary poisoning from rodenticides and collisions with high-speed vehicles.",
        "facts": "A Barn Owl's ears are asymmetrical, enabling it to map sound in 3D to hunt in complete darkness.",
    },

    "Peregrine Falcon": {
        "scientific_name": "Falco peregrinus",
        "type": "Animal / Bird",
        "family": "Falconidae",
        "habitat": "Cliffs, river valleys, mountain ranges, and skyscraper-heavy cities worldwide",
        "region": "Worldwide (all continents except Antarctica)",
        "ecological_role": "Aerial raptor regulating pigeon, dove, and waterfowl populations.",
        "importance": "Fastest animal on Earth; benchmark species for pesticide monitoring.",
        "conservation": "Least Concern (Recovered from DDT)",
        "conserved": True,
        "estimated_population": "~340,000 globally",
        "diet": "Carnivorous (Medium-sized birds like pigeons, ducks, and songbirds)",
        "threats": "Illegal nest raiding, building collisions, and chemical pollution.",
        "facts": "When hunting, the peregrine falcon drops in a vertical dive (stoop) reaching speeds over 320 km/h (200 mph).",
    },

    "Bald Eagle": {
        "scientific_name": "Haliaeetus leucocephalus",
        "type": "Animal / Bird",
        "family": "Accipitridae",
        "habitat": "Coniferous and deciduous forests near large open bodies of water in North America",
        "region": "North America (USA, Canada, Mexico)",
        "ecological_role": "Apex predator and scavenger regulating fish and waterfowl numbers.",
        "importance": "National emblem of the USA; a historic conservation recovery success story.",
        "conservation": "Least Concern (Widespread)",
        "conserved": True,
        "estimated_population": "~300,000 in North America",
        "diet": "Carnivorous (Fish, water birds, carrion, small mammals)",
        "threats": "Lead poisoning from carcasses, illegal shooting, and nesting tree loss.",
        "facts": "A Bald Eagle's nest can weigh up to 1 ton and measure 3 meters wide, built high in dominant forest canopies.",
    },

    "Emperor Penguin": {
        "scientific_name": "Aptenodytes forsteri",
        "type": "Animal / Bird",
        "family": "Spheniscidae",
        "habitat": "Antarctic pack ice and surrounding cold sub-Antarctic waters",
        "region": "Antarctica",
        "ecological_role": "Mid-level predator regulating krill, fish, and squid populations.",
        "importance": "Key indicator species for polar climate stability.",
        "conservation": "Near Threatened",
        "conserved": True,
        "estimated_population": "~595,000 breeding adults",
        "diet": "Carnivorous (Fish, krill, squid)",
        "threats": "Loss of sea ice nesting grounds, overfishing of krill, and warming currents.",
        "facts": "Emperor penguins endure winter temperatures of -60°C (-76°F) by huddling together in massive, rotating circles.",
    },

    "Blue Jay": {
        "scientific_name": "Cyanocitta cristata",
        "type": "Animal / Bird",
        "family": "Corvidae",
        "habitat": "Deciduous and mixed forests, gardens, and urban parks in North America",
        "region": "North America (Eastern and Central USA, Canada)",
        "ecological_role": "Seed disperser; feeds on oak acorns, actively planting future forests.",
        "importance": "Highly intelligent songbird with complex communication behaviors.",
        "conservation": "Least Concern (Widespread)",
        "conserved": False,
        "estimated_population": "~13 million in the wild",
        "diet": "Omnivorous (Acorns, seeds, nuts, beetles, grasshoppers, small frogs)",
        "threats": "West Nile Virus and habitat fragmentation.",
        "facts": "Blue Jays can imitate the calls of local hawks to warn others or scare competitor birds away from food.",
    },

    "Wandering Albatross": {
        "scientific_name": "Diomedea exulans",
        "type": "Animal / Bird",
        "family": "Diomedeidae",
        "habitat": "Sub-Antarctic oceans, islands, and open marine waters",
        "region": "Southern Ocean (Antarctica, sub-Antarctic islands)",
        "ecological_role": "Pelagic scavenger regulating open-sea squid and fish populations.",
        "importance": "Possesses the largest wingspan of any living bird.",
        "conservation": "Vulnerable",
        "conserved": True,
        "estimated_population": "~20,000 individuals",
        "diet": "Carnivorous (Squid, small fish, crustaceans, fisheries waste)",
        "threats": "Longline fishing hook entanglements and ingestion of marine plastic pollution.",
        "facts": "The Wandering Albatross can glide for hours over the ocean without flapping its wings, using dynamic soaring.",
    },

    # ==================== AMPHIBIANS ====================

    "Indian Bullfrog": {
        "scientific_name": "Hoplobatrachus tigerinus",
        "type": "Animal / Amphibian",
        "family": "Dicroglossidae",
        "habitat": "Freshwater wetlands, rice paddies, quiet forest pools, and marshes",
        "region": "Indian Subcontinent (India, Bangladesh, Nepal, Myanmar)",
        "ecological_role": "Controls agricultural insect pests; tadpoles control algae growth.",
        "importance": "Major insect regulator in wetland ecosystems across South Asia.",
        "conservation": "Least Concern (Widespread)",
        "conserved": False,
        "estimated_population": "Abundant (estimated over 10 million)",
        "diet": "Carnivorous (Insects, earthworms, small fish, young frogs, mice)",
        "threats": "Pesticide runoffs in agricultural lands and habitat drainage.",
        "facts": "During the monsoon breeding season, male Indian bullfrogs turn bright yellow and inflate blue vocal sacs.",
    },

    "Purple Frog": {
        "scientific_name": "Nasikabatrachus sahyadrensis",
        "type": "Animal / Amphibian",
        "family": "Nasikabatrachidae",
        "habitat": "Underground soil burrows near forest streams in the Western Ghats, India",
        "region": "Western Ghats, India (endemic)",
        "ecological_role": "Predator of subterranean termites and soil invertebrates.",
        "importance": "Evolutionary relict representing a lineage separate for over 100 million years.",
        "conservation": "Endangered",
        "conserved": True,
        "estimated_population": "Rare (estimated under 5,000 individuals)",
        "diet": "Insectivorous (primarily Termites)",
        "threats": "Forest clearance for plantations, dam construction, and stream diversion.",
        "facts": "The purple frog spends 363 days a year underground, emerging for only 2 weeks to breed in monsoonal streams.",
    },

    "Malabar Gliding Frog": {
        "scientific_name": "Rhacophorus malabaricus",
        "type": "Animal / Amphibian",
        "family": "Rhacophoridae",
        "habitat": "Canopy layer of moist tropical rainforests of the Western Ghats, India",
        "region": "Western Ghats, India (endemic)",
        "ecological_role": "Arboreal insect predator; tadpoles support forest pool food chains.",
        "importance": "Highly specialized tree frog exhibiting glide adaptation.",
        "conservation": "Least Concern (Fragile habitat)",
        "conserved": True,
        "estimated_population": "Stable (locally common)",
        "diet": "Insectivorous (Flies, beetles, crickets, tree moths)",
        "threats": "Rainforest fragmentation and climate-driven drying of canopies.",
        "facts": "This frog can glide up to 12 meters from tree branches using large webbed feet as natural parachutes.",
    },

    "Fire Salamander": {
        "scientific_name": "Salamandra salamandra",
        "type": "Animal / Amphibian",
        "family": "Salamandridae",
        "habitat": "Deciduous forests, hilly damp woodlands, and mossy crevices in Europe",
        "region": "Europe (Central and Southern Europe)",
        "ecological_role": "Controls forest floor invertebrates; indicators of healthy, damp leaf litter.",
        "importance": "Symbol of folklore; model organism in developmental biology.",
        "conservation": "Least Concern (Declining locally)",
        "conserved": True,
        "estimated_population": "Over 500,000 (declining in northern areas)",
        "diet": "Carnivorous (Earthworms, slugs, beetles, spiders)",
        "threats": "Bsal chytrid fungus pandemic, road mortalities, and wetland drainage.",
        "facts": "The fire salamander does not lay eggs; females deposit fully formed larvae directly into clean forest streams.",
    },

    "Axolotl": {
        "scientific_name": "Ambystoma mexicanum",
        "type": "Animal / Amphibian",
        "family": "Ambystomatidae",
        "habitat": "Freshwater lake complex of Xochimilco near Mexico City",
        "region": "Mexico (Lake Xochimilco, Mexico City)",
        "ecological_role": "Top predator in its endemic lake ecosystem, feeding on aquatic insects.",
        "importance": "Renowned for its ability to regenerate entire limbs, heart tissue, and parts of its brain.",
        "conservation": "Critically Endangered",
        "conserved": True,
        "estimated_population": "Fewer than 1,000 left in the wild",
        "diet": "Carnivorous (Water fleas, insect larvae, worms, small fish)",
        "threats": "Water pollution, lake drainage, and predation by invasive tilapia and carp.",
        "facts": "Axolotls exhibit neoteny, meaning they reach reproductive maturity without ever undergoing metamorphosis into land salamanders.",
    },

    "American Bullfrog": {
        "scientific_name": "Lithobates catesbeianus",
        "type": "Animal / Amphibian",
        "family": "Ranidae",
        "habitat": "Quiet warm freshwater lakes, sluggish rivers, marshes, and farm ponds",
        "region": "North America (Eastern USA, Canada)",
        "ecological_role": "Voracious predator; serves as a major food source for herons and raccoons.",
        "importance": "Often invasive when introduced, outcompeting local amphibians.",
        "conservation": "Least Concern (Widespread)",
        "conserved": False,
        "estimated_population": "Abundant (millions globally)",
        "diet": "Carnivorous (Insects, crayfish, worms, smaller frogs, mice, baby birds)",
        "threats": "Chytrid fungus carrier (resilient), water pollution, and drainage.",
        "facts": "A female American bullfrog can deposit up to 20,000 eggs in a single floating sheet.",
    },

    "Cane Toad": {
        "scientific_name": "Rhinella marina",
        "type": "Animal / Amphibian",
        "family": "Bufonidae",
        "habitat": "Forests, agricultural fields, gardens, and coastal marshes",
        "region": "Central and South America (invasive in Australia)",
        "ecological_role": "Introduced species that has caused severe ecological disruption in Australia and islands.",
        "importance": "Iconic case study of biological control failure.",
        "conservation": "Least Concern (Highly Invasive)",
        "conserved": False,
        "estimated_population": "Over 200 million in Australia alone",
        "diet": "Omnivorous (Insects, small mammals, domestic pet food, carrion)",
        "threats": "Actively culled in invasive zones.",
        "facts": "Cane toads secrete a potent bufotoxin from parotoid glands behind their eyes, lethal to native predators.",
    },

    # ==================== AQUATIC ANIMALS ====================

    "Blue Whale": {
        "scientific_name": "Balaenoptera musculus",
        "type": "Animal / Aquatic",
        "family": "Balaenopteridae",
        "habitat": "Deep open ocean waters globally, migrating between polar feeding and tropical breeding zones",
        "region": "All major oceans worldwide",
        "ecological_role": "Consumes massive amounts of krill; whale fall carcasses feed deep-sea ecosystems for decades.",
        "importance": "The largest animal ever known to have lived on Earth.",
        "conservation": "Endangered",
        "conserved": True,
        "estimated_population": "~10,000 - 25,000 in the wild",
        "diet": "Planktonic (primarily Krill)",
        "threats": "Ship collisions, ocean noise, entanglement in ghost nets, and climate-driven krill declines.",
        "facts": "A blue whale's heart is the size of a small car, and its tongue can weigh as much as an entire elephant.",
    },

    "Great White Shark": {
        "scientific_name": "Carcharodon carcharias",
        "type": "Animal / Aquatic",
        "family": "Lamnidae",
        "habitat": "Temperate and subtropical coastal waters globally",
        "region": "Coastal waters worldwide (temperate and subtropical oceans)",
        "ecological_role": "Apex marine predator regulating marine mammal and fish populations.",
        "importance": "Crucial for marine ecological balance; highly studied for physiological thermoregulation.",
        "conservation": "Vulnerable",
        "conserved": True,
        "estimated_population": "~3,000 - 5,000 in the wild",
        "diet": "Carnivorous (Seals, sea lions, dolphins, tuna, rays)",
        "threats": "Overfishing, shark finning, gill net accidental catches, and plastic pollution.",
        "facts": "Great white sharks can detect a single drop of blood in 100 liters of water and sense electrical fields of prey.",
    },

    "Bottlenose Dolphin": {
        "scientific_name": "Tursiops truncatus",
        "type": "Animal / Aquatic",
        "family": "Delphinidae",
        "habitat": "Warm and temperate oceans, bays, lagoons, and river mouth estuaries",
        "region": "Temperate and tropical oceans worldwide",
        "ecological_role": "Apex predator controlling schooling fish and squid populations.",
        "importance": "Highly intelligent cetacean; key species in marine cognitive science.",
        "conservation": "Least Concern (Widespread)",
        "conserved": True,
        "estimated_population": "~600,000 globally",
        "diet": "Carnivorous (Mullet, croaker, sea bass, squid, crabs)",
        "threats": "Fisheries entanglement, marine noise pollution, and chemical contamination.",
        "facts": "Dolphins use echolocation to navigate and have signature whistles that act as unique names.",
    },

    "Green Sea Turtle": {
        "scientific_name": "Chelonia mydas",
        "type": "Animal / Aquatic",
        "family": "Cheloniidae",
        "habitat": "Tropical and subtropical seagrass pastures, coral reefs, and nesting beaches",
        "region": "Tropical and subtropical oceans worldwide",
        "ecological_role": "Maintains seagrass health by grazing, aiding productivity; shells provide habitat for epibionts.",
        "importance": "Keystone species representing health of coral reefs and marine grass ecosystems.",
        "conservation": "Endangered",
        "conserved": True,
        "estimated_population": "~85,000 nesting females",
        "diet": "Herbivorous as adults (Seagrasses, algae)",
        "threats": "Nesting beach destruction, egg poaching, boat strikes, and marine debris ingestion.",
        "facts": "Green sea turtles return to the exact beach where they hatched to lay their own eggs, navigating by magnetic fields.",
    },

    "Clownfish": {
        "scientific_name": "Amphiprioninae (subfamily)",
        "type": "Animal / Aquatic",
        "family": "Pomacentridae",
        "habitat": "Warm water coral reefs of the Indo-Pacific, sheltered in sea anemones",
        "region": "Indo-Pacific region (Indian Ocean, Pacific Ocean)",
        "ecological_role": "Mutualistic partner with sea anemones, cleaning tentacles and deterring predators.",
        "importance": "Iconic reef species; highly popular in aquarium trade.",
        "conservation": "Least Concern (Locally threatened)",
        "conserved": False,
        "estimated_population": "Common in coral reef zones",
        "diet": "Omnivorous (Algae, zooplankton, anemone scraps)",
        "threats": "Coral bleaching, acidification, and over-harvesting for aquariums.",
        "facts": "All clownfish are born male; they can change gender to become the dominant female of their anemone host.",
    },

    "Giant Pacific Octopus": {
        "scientific_name": "Enteroctopus dofleini",
        "type": "Animal / Aquatic",
        "family": "Octopodidae",
        "habitat": "Cold temperate coastal waters and intertidal zones of the North Pacific",
        "region": "North Pacific Ocean (Alaska to Japan)",
        "ecological_role": "Predator of crabs and bivalves; prey for seals, sea otters, and large fish.",
        "importance": "Largest and longest-lived octopus species; highly intelligent.",
        "conservation": "Least Concern (Not well surveyed)",
        "conserved": False,
        "estimated_population": "Unknown (widespread in deep shelf waters)",
        "diet": "Carnivorous (Crabs, lobsters, clams, fish, other octopuses)",
        "threats": "Overfishing, toxic runoffs, and ocean warming.",
        "facts": "Giant Pacific octopuses have three hearts, blue copper-based blood, and can solve complex mazes.",
    },

    "Manatee": {
        "scientific_name": "Trichechus (genus)",
        "type": "Animal / Aquatic",
        "family": "Trichechidae",
        "habitat": "Warm, shallow freshwater rivers, estuaries, and coastal seagrass beds",
        "region": "Atlantic coast (USA — Florida, Caribbean, West Africa)",
        "ecological_role": "Consumes massive quantities of aquatic plants, preventing choked waterways.",
        "importance": "Known as 'sea cows'; flagship species for wetland and coastal protection.",
        "conservation": "Vulnerable (Threatened)",
        "conserved": True,
        "estimated_population": "~13,000 globally",
        "diet": "Herbivorous (Seagrasses, water lettuce, mangrove leaves)",
        "threats": "Boat propeller strikes, habitat loss, and toxic red tide algae blooms.",
        "facts": "Manatees are closely related to elephants, possessing similar thick grey skin and vocalizing with high squeaks.",
    },

    "Killer Whale": {
        "scientific_name": "Orcinus orca",
        "type": "Animal / Aquatic",
        "family": "Delphinidae",
        "habitat": "Open oceans globally, from freezing polar ice caps to warm tropical seas",
        "region": "All major oceans worldwide (from Arctic to Antarctic)",
        "ecological_role": "Apex marine predator regulating fish, seal, and whale populations.",
        "importance": "Highly intelligent marine mammal; apex predator of the global ocean.",
        "conservation": "Data Deficient (Subpopulations Endangered)",
        "conserved": True,
        "estimated_population": "~50,000 globally in the wild",
        "diet": "Carnivorous (Salmon, seals, sea lions, rays, sharks, baleen whales)",
        "threats": "Chemical bioaccumulation (PCBs), noise pollution, and salmon stock depletion.",
        "facts": "Killer whales (Orcas) live in matriarchal pods and have distinct hunting techniques passed down generations.",
    },

    "Sea Otter": {
        "scientific_name": "Enhydra lutris",
        "type": "Animal / Aquatic",
        "family": "Mustelidae",
        "habitat": "Coastal shallow waters and kelp forests of the North Pacific",
        "region": "North Pacific Ocean (Alaska, California, Russia, Japan)",
        "ecological_role": "Keystone species that controls sea urchin populations, protecting kelp forests.",
        "importance": "Vital for kelp carbon storage preservation; indicator of coastal health.",
        "conservation": "Endangered",
        "conserved": True,
        "estimated_population": "~125,000 globally",
        "diet": "Carnivorous (Sea urchins, abalone, crabs, clams, sea snails)",
        "threats": "Oil spills, shark bites, toxic algae, and commercial fishing gear.",
        "facts": "Sea otters have the densest fur of any mammal — up to 1 million hairs per square inch — and no blubber.",
    },

    "Leatherback Sea Turtle": {
        "scientific_name": "Dermochelys coriacea",
        "type": "Animal / Aquatic",
        "family": "Dermochelyidae",
        "habitat": "Open oceans globally, nesting on tropical sandy beaches",
        "region": "All major oceans worldwide (widest range of any sea turtle)",
        "ecological_role": "Controls jellyfish populations, maintaining open sea balances.",
        "importance": "Largest living turtle and the deepest-diving reptile.",
        "conservation": "Vulnerable (Critically Endangered in Pacific)",
        "conserved": True,
        "estimated_population": "~30,000 - 40,000 nesting females",
        "diet": "Carnivorous (primarily Jellyfish and salps)",
        "threats": "Plastic ingestion (mistaking bags for jellyfish), egg harvesting, and longline fishing.",
        "facts": "The leatherback lacks a hard shell, instead possessing a flexible, leathery skin overlaying osteoderms.",
    },

    "Coral Polyps": {
        "scientific_name": "Anthozoa (class)",
        "type": "Animal / Aquatic",
        "family": "Various coral families",
        "habitat": "Shallow, warm marine waters with high sunlight penetration",
        "region": "Tropical oceans worldwide (Indo-Pacific, Caribbean, Red Sea)",
        "ecological_role": "Builds coral reefs that support 25% of all marine life despite covering <0.1% of the ocean.",
        "importance": "Foundation of global marine biodiversity; protects coastlines from storms.",
        "conservation": "Threatened (Critically threatened globally)",
        "conserved": True,
        "estimated_population": "Trillions of polyps (coral covers ~284,000 sq km)",
        "diet": "Omnivorous (Symbiotic zooxanthellae photosynthesis, zooplankton capture)",
        "threats": "Ocean warming, acidification, blast fishing, and sediment runoff.",
        "facts": "Corals are tiny colonial animals that secrete calcium carbonate skeletons to build reef structures.",
    },
}

SPECIES_NAME_MAP = {
    # Plants
    "neem": "Neem", "azadirachta indica": "Neem", "azadirachta": "Neem",
    "banyan": "Banyan", "ficus benghalensis": "Banyan", "indian banyan": "Banyan",
    "teak": "Teak", "tectona grandis": "Teak", "tectona": "Teak",
    "sal": "Sal Tree", "shorea robusta": "Sal Tree", "sal tree": "Sal Tree",
    "peepal": "Peepal", "ficus religiosa": "Peepal", "sacred fig": "Peepal", "bodhi tree": "Peepal",
    "mango": "Mango", "mangifera indica": "Mango", "mangifera": "Mango",
    "coconut": "Coconut Palm", "cocos nucifera": "Coconut Palm", "coconut palm": "Coconut Palm",
    "bamboo": "Bamboo", "bambusoideae": "Bamboo",
    "eucalyptus": "Eucalyptus", "eucalyptus globulus": "Eucalyptus",
    "pine": "Pine", "pinus": "Pine", "pine tree": "Pine",
    "oak": "Oak", "quercus": "Oak", "oak tree": "Oak",
    "willow": "Willow", "salix": "Willow", "weeping willow": "Willow",
    "maple": "Maple", "acer": "Maple", "maple tree": "Maple",
    "hibiscus": "Hibiscus", "hibiscus rosa-sinensis": "Hibiscus", "china rose": "Hibiscus",
    "sunflower": "Sunflower", "helianthus annuus": "Sunflower", "helianthus": "Sunflower",
    "rose": "Rose", "rosa": "Rose",
    "jasmine": "Jasmine", "jasminum": "Jasmine",
    "marigold": "Marigold", "tagetes": "Marigold",
    "lavender": "Lavender", "lavandula": "Lavender",
    "orchid": "Orchid", "orchidaceae": "Orchid", "phalaenopsis": "Orchid",
    "bougainvillea": "Bougainvillea",
    "daisy": "Daisy", "bellis perennis": "Daisy", "bellis": "Daisy",
    "lily": "Lily", "lilium": "Lily",
    "chrysanthemum": "Chrysanthemum", "mums": "Chrysanthemum",
    "tulsi": "Tulsi (Holy Basil)", "holy basil": "Tulsi (Holy Basil)", "ocimum sanctum": "Tulsi (Holy Basil)",
    "basil": "Tulsi (Holy Basil)", "ocimum": "Tulsi (Holy Basil)",
    "mint": "Mint", "mentha": "Mint", "peppermint": "Mint", "spearmint": "Mint",
    "coriander": "Coriander (Cilantro)", "cilantro": "Coriander (Cilantro)", "coriandrum": "Coriander (Cilantro)",
    "fern": "Fern", "polypodiopsida": "Fern",
    "aloe": "Aloe Vera", "aloe vera": "Aloe Vera", "aloe barbadensis": "Aloe Vera",
    "cactus": "Cactus", "cactaceae": "Cactus", "opuntia": "Cactus", "saguaro": "Cactus",
    "jade plant": "Jade Plant", "crassula ovata": "Jade Plant", "crassula": "Jade Plant",

    # Aquatic Plants
    "lotus": "Lotus", "nelumbo nucifera": "Lotus", "nelumbo": "Lotus",
    "water lily": "Water Lily", "nymphaea": "Water Lily", "nymphaeaceae": "Water Lily",
    "water hyacinth": "Water Hyacinth", "eichhornia crassipes": "Water Hyacinth", "eichhornia": "Water Hyacinth",
    "duckweed": "Duckweed", "lemnoideae": "Duckweed", "lemna": "Duckweed",
    "eelgrass": "Eelgrass", "zostera": "Eelgrass", "zostera marina": "Eelgrass",
    "hydrilla": "Hydrilla", "hydrilla verticillata": "Hydrilla",
    "coontail": "Coontail", "ceratophyllum demersum": "Coontail", "ceratophyllum": "Coontail",

    # Animals
    "tiger": "Bengal Tiger", "bengal tiger": "Bengal Tiger", "panthera tigris": "Bengal Tiger",
    "elephant": "Indian Elephant", "indian elephant": "Indian Elephant", "elephas maximus": "Indian Elephant",
    "leopard": "Indian Leopard", "indian leopard": "Indian Leopard", "panthera pardus": "Indian Leopard",
    "lion": "Asiatic Lion", "panthera leo": "Asiatic Lion", "asiatic lion": "Asiatic Lion",
    "wolf": "Wolf", "canis lupus": "Wolf", "gray wolf": "Wolf", "grey wolf": "Wolf",
    "red panda": "Red Panda", "ailurus fulgens": "Red Panda",
    "deer": "Spotted Deer", "spotted deer": "Spotted Deer", "chital": "Spotted Deer", "axis axis": "Spotted Deer",
    "bear": "Sloth Bear", "sloth bear": "Sloth Bear", "melursus ursinus": "Sloth Bear",
    "monkey": "Rhesus Macaque", "macaque": "Rhesus Macaque", "rhesus": "Rhesus Macaque", "macaca mulatta": "Rhesus Macaque",
    "fox": "Red Fox", "red fox": "Red Fox", "vulpes vulpes": "Red Fox", "vulpes": "Red Fox",
    "panda": "Giant Panda", "giant panda": "Giant Panda", "ailuropoda": "Giant Panda",
    "cheetah": "Cheetah", "acinonyx": "Cheetah", "acinonyx jubatus": "Cheetah",
    "grizzly": "Grizzly Bear", "grizzly bear": "Grizzly Bear",
    "kangaroo": "Red Kangaroo", "red kangaroo": "Red Kangaroo",
    "platypus": "Platypus", "ornithorhynchus": "Platypus",

    # Birds
    "peacock": "Indian Peafowl", "peafowl": "Indian Peafowl", "pavo cristatus": "Indian Peafowl",
    "parakeet": "Rose-ringed Parakeet", "rose-ringed parakeet": "Rose-ringed Parakeet", "psittacula": "Rose-ringed Parakeet",
    "eagle": "Golden Eagle", "golden eagle": "Golden Eagle", "aquila chrysaetos": "Golden Eagle",
    "kingfisher": "Common Kingfisher", "common kingfisher": "Common Kingfisher", "alcedo atthis": "Common Kingfisher",
    "owl": "Barn Owl", "barn owl": "Barn Owl", "tyto alba": "Barn Owl",
    "falcon": "Peregrine Falcon", "peregrine falcon": "Peregrine Falcon", "falco peregrinus": "Peregrine Falcon",
    "bald eagle": "Bald Eagle", "haliaeetus": "Bald Eagle",
    "penguin": "Emperor Penguin", "emperor penguin": "Emperor Penguin",
    "blue jay": "Blue Jay", "cyanocitta": "Blue Jay",
    "albatross": "Wandering Albatross", "wandering albatross": "Wandering Albatross",

    # Amphibians
    "frog": "Indian Bullfrog", "bullfrog": "Indian Bullfrog", "hoplobatrachus": "Indian Bullfrog",
    "purple frog": "Purple Frog", "nasikabatrachus": "Purple Frog",
    "gliding frog": "Malabar Gliding Frog", "malabar gliding frog": "Malabar Gliding Frog",
    "salamander": "Fire Salamander", "fire salamander": "Fire Salamander",
    "axolotl": "Axolotl", "ambystoma": "Axolotl",
    "american bullfrog": "American Bullfrog", "lithobates": "American Bullfrog",
    "cane toad": "Cane Toad", "rhinella": "Cane Toad",

    # Aquatic Animals
    "blue whale": "Blue Whale", "balaenoptera": "Blue Whale",
    "shark": "Great White Shark", "great white shark": "Great White Shark", "carcharodon": "Great White Shark",
    "dolphin": "Bottlenose Dolphin", "bottlenose dolphin": "Bottlenose Dolphin", "tursiops": "Bottlenose Dolphin",
    "sea turtle": "Green Sea Turtle", "green sea turtle": "Green Sea Turtle", "chelonia": "Green Sea Turtle",
    "clownfish": "Clownfish", "amphiprion": "Clownfish",
    "octopus": "Giant Pacific Octopus", "giant pacific octopus": "Giant Pacific Octopus",
    "manatee": "Manatee", "trichechus": "Manatee",
    "orca": "Killer Whale", "killer whale": "Killer Whale",
    "sea otter": "Sea Otter", "enhudra": "Sea Otter",
    "leatherback": "Leatherback Sea Turtle", "leatherback sea turtle": "Leatherback Sea Turtle",
    "coral": "Coral Polyps", "coral polyps": "Coral Polyps",
}
